In [6]:
import numpy as np

N = 5
M = 4

A = np.random.randint(1, 100, size=(N, M))

sums = np.sum(np.abs(A), axis=0)
max_col_index = np.argmax(sums)

min_element = np.min(A[:, max_col_index])

print(A)
print("Стовпець з максимальною сумою абсолютних значень елементів:", max_col_index)
print("Найменший елемент у цьому стовпці:", min_element)

[[64  8 13 54]
 [57 61 75 95]
 [49 51 72 42]
 [31 57  8 31]
 [49 19 32 50]]
Стовпець з максимальною сумою абсолютних значень елементів: 3
Найменший елемент у цьому стовпці: 31
